import { redirect } from "next/navigation";
import { createSupabaseServer } from "@/lib/supabase";
import { parseJSON } from "@/lib/utils";
import { ClauseCard, MissingProtectionCard } from "@/app/components/Cards";
import { RiskScoreMeter } from "@/app/components/RiskScoreMeter";
import { VerdictBadge } from "@/app/components/Badges";
import { PrintButton } from "@/app/components/PrintButton";

export default async function ReportPage({ params }: { params: { id: string } }) {
  const supabase = createSupabaseServer();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth");

  const { data } = await supabase.from("analyses").select("*").eq("id", params.id).eq("user_id", user.id).single();
  if (!data) redirect("/dashboard");

  const clauses = parseJSON<any[]>(data.clauses, []).sort((a, b) => (a.severity === "high" ? -1 : 1));
  const missing = parseJSON<any[]>(data.missing_protections, []).sort((a, b) => (a.severity === "high" ? -1 : 1));
  const dates = parseJSON<any[]>(data.key_dates, []);
  const financial = parseJSON<any[]>(data.financial_exposure, []);

  return (
    <main className="mx-auto max-w-6xl space-y-8 px-6 py-10">
      <header className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="font-serif text-3xl">{data.filename}</h1>
          <p className="text-sm text-secondary">{new Date(data.created_at).toLocaleString("en-GB")} · {data.word_count} words</p>
        </div>
        <div className="no-print"><PrintButton /></div>
      </header>

      <section className="rounded-2xl border border-border bg-white p-6">
        <div className="flex items-center justify-between">
          <RiskScoreMeter score={data.risk_score ?? 0} />
          <VerdictBadge verdict={data.verdict || "Caution"} />
        </div>
        <p className="mt-3 text-secondary">{data.justification}</p>
        <div className="mt-4 rounded-lg bg-warning/10 p-3">⚠️ Most Important: {data.top_concern}</div>
      </section>

      <section className="rounded-xl border border-border bg-white p-6"><h2 className="font-serif text-2xl">What you&apos;re actually agreeing to</h2><p className="mt-3">{data.summary}</p></section>

      <section className="grid gap-4 rounded-xl border border-border bg-white p-6 md:grid-cols-5 text-sm">
        <div><p className="text-secondary">Document Type</p><p>{data.document_type || "—"}</p></div>
        <div><p className="text-secondary">Governing Law</p><p>{data.governing_law || "—"}</p></div>
        <div><p className="text-secondary">Contract Duration</p><p>{data.contract_duration || "—"}</p></div>
        <div><p className="text-secondary">Notice Period</p><p>{data.notice_period || "—"}</p></div>
        <div><p className="text-secondary">Parties</p><p>{parseJSON<string[]>(data.parties, []).join(", ") || "—"}</p></div>
      </section>

      {data.missing_count > 0 && (
        <section className="space-y-4">
          <h2 className="rounded-lg bg-danger px-4 py-3 text-white">{data.missing_count} Critical Protections Missing</h2>
          {missing.map((item) => <MissingProtectionCard key={item.name} item={item} />)}
        </section>
      )}

      <section className="space-y-4">
        <h2 className="font-serif text-2xl">🔴 Risk Clauses</h2>
        {clauses.map((clause, index) => <ClauseCard key={index} clause={clause} />)}
      </section>

      <section className="grid gap-6 md:grid-cols-2">
        <div className="rounded-xl border border-border bg-white p-6"><h3 className="font-serif text-xl">📅 Key Dates</h3><ul className="mt-3 space-y-2">{dates.map((d, i) => <li key={i}>📅 {d.label}: {d.date}</li>)}</ul></div>
        <div className="rounded-xl border border-border bg-white p-6"><h3 className="font-serif text-xl">💰 Financial Exposure</h3><ul className="mt-3 space-y-2">{financial.map((f, i) => <li key={i}>{f.item}: {f.value}</li>)}</ul><p className="mt-4 font-semibold">Liability Cap: {data.contract_value || "Uncapped ⚠️"}</p></div>
      </section>

      <p className="text-xs text-secondary">Analysis quality score: {data.quality_score}/10 — reviewed by AI QA agent</p>
      <p className="text-xs text-secondary">This report is generated by AI for informational purposes only and does not constitute legal advice. Always consult a qualified solicitor before signing any contract.</p>
    </main>
  );
}
