import { ClauseCard, MissingProtectionCard } from "@/app/components/Cards";
import { RiskScoreMeter } from "@/app/components/RiskScoreMeter";
import { VerdictBadge } from "@/app/components/Badges";

const sample = {
  filename: "subcontractor-agreement.pdf",
  risk_score: 8,
  verdict: "High Risk",
  top_concern: "Unlimited liability applies to all indirect losses.",
  summary: "This contract heavily favours the client with broad termination rights and limited payment protections for the contractor.",
  missing_count: 2,
  missing: [
    { name: "Data Processing Clause", severity: "high", explanation: "No GDPR processing obligations are defined.", recommendation: "Add compliant data processor terms." },
    { name: "Termination for Convenience Notice", severity: "medium", explanation: "No minimum notice period included.", recommendation: "Set a 30-day minimum notice." }
  ],
  clauses: [
    { severity: "high", type: "Liability", is_common: false, clause_text: "The Supplier accepts unlimited liability.", reason: "This exposes you to uncapped claims.", common_context: "Most UK SME contracts cap liability to fees paid or a fixed amount." },
    { severity: "medium", type: "Payment", is_common: true, clause_text: "Invoices paid within 60 days.", reason: "Long payment window may impact cashflow.", common_context: "30-day windows are more common among SMEs." }
  ]
};

export default function SampleReportPage() {
  return (
    <main className="mx-auto max-w-6xl space-y-8 px-6 py-10">
      <h1 className="font-serif text-4xl">Sample Report</h1>
      <section className="rounded-xl border border-border bg-white p-6"><div className="flex items-center justify-between"><RiskScoreMeter score={sample.risk_score} /><VerdictBadge verdict={sample.verdict} /></div><div className="mt-4 rounded-lg bg-warning/10 p-3">⚠️ Most Important: {sample.top_concern}</div></section>
      <section className="rounded-xl border border-border bg-white p-6"><h2 className="font-serif text-2xl">What you&apos;re actually agreeing to</h2><p className="mt-3">{sample.summary}</p></section>
      <section className="space-y-3"><h2 className="rounded-lg bg-danger px-4 py-3 text-white">{sample.missing_count} Critical Protections Missing</h2>{sample.missing.map((m) => <MissingProtectionCard key={m.name} item={m} />)}</section>
      <section className="space-y-3"><h2 className="font-serif text-2xl">🔴 Risk Clauses</h2>{sample.clauses.map((c, i) => <ClauseCard key={i} clause={c} />)}</section>
      <p className="text-xs text-secondary">This report is generated by AI for informational purposes only and does not constitute legal advice.</p>
    </main>
  );
}
